version: "3"

services:
  db:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    networks:
      - db
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - redis

networks:
  db:
  redis:
  mailer:
